
import java.util.Timer;
import java.util.TimerTask;

/**
 * Bresenham's Line Algorithm test
 * 
 * @author leo
 */
public class ViewAsciiText extends javax.swing.JFrame {
    
    private double angle;
    private final char[] chars = { ' ', '#', '@' };

    /**
     * Creates new form ViewTextAscii
     */
    public ViewAsciiText() {
        initComponents();
    }
    
    public void startMainLoop() {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                update();
                renderScreen();
            }
        }, 100, 1000 / 30);
    }
    
    private void update() {
        BresenhamLine.clearScreen();
        for (int a = 0; a < 360; a += 30) {
            int x = (int) (50 * Math.cos(Math.toRadians(a + angle)));
            int y = (int) (25 * Math.sin(Math.toRadians(a + angle)));
            angle += 0.1;
            BresenhamLine.drawLine(55, 25, 55 + x, 25 + y);
        }
    }
    
    private final StringBuilder screenText = new StringBuilder();
    
    private void renderScreen() {
        screenText.setLength(0);
        for (int y = 0; y < 50; y++) {
            int[] screen = BresenhamLine.screen[y];
            for (int x = 0; x < 110; x++) {
                char c = chars[screen[x]];
                screenText.append(c);
            }
            screenText.append('\n');
        }
        txt.setText(screenText.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt.setColumns(110);
        txt.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAsciiText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAsciiText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAsciiText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAsciiText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewAsciiText frame = new ViewAsciiText();
                frame.setTitle("Bresenham's Line Algorithm Test");
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
                frame.startMainLoop();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
